TARFILES = Makefile scanner.mll parser.mly ast.mli next.ml

OBJS = parser.cmo scanner.cmo next.cmo
LIBPATH = -I +sdl

next : $(OBJS)
	ocamlc -o next $(OBJS)

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc -v parser.mly

%.cmo : %.ml
	ocamlc -c $(LIBPATH) $<

%.cmi : %.mli
	ocamlc -c $(LIBPATH) $<

next.tar.gz : $(TARFILES)
	cd .. && tar zcf next/next.tar.gz $(TARFILES:%=next/%)

.PHONY : clean
clean :
	rm -f next parser.ml parser.mli scanner.ml *.cmo *.cmi

# Generated by ocamldep *.ml *.mli
next.cmo: scanner.cmo parser.cmi ast.cmi 
next.cmx: scanner.cmx parser.cmx ast.cmi 
parser.cmo: ast.cmi parser.cmi 
parser.cmx: ast.cmi parser.cmi 
scanner.cmo: parser.cmi 
scanner.cmx: parser.cmx 
parser.cmi: ast.cmi 
